// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/Mhbib34/missing-person-service/internal/controller"
	"github.com/Mhbib34/missing-person-service/internal/database"
	"github.com/Mhbib34/missing-person-service/internal/repository"
	"github.com/Mhbib34/missing-person-service/internal/router"
	"github.com/Mhbib34/missing-person-service/internal/usecase"
	"github.com/Mhbib34/missing-person-service/internal/worker"
	"github.com/gin-gonic/gin"
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from injector.go:

func InitializeServer() (*App, error) {
	db, err := database.Connect()
	if err != nil {
		return nil, err
	}
	missingPersonRepository := repository.NewMissingPersonRepository(db)
	validate := NewValidator()
	missingPersonUsecase := usecase.NewMissingPersonUsecase(missingPersonRepository, validate)
	missingPersonController := controller.NewMissingPersonController(missingPersonUsecase)
	engine := router.SetupRouter(missingPersonController)
	resizeImageJobWorker := provideResizeImageWorker(db)
	app := &App{
		DB:     db,
		Router: engine,
		Worker: resizeImageJobWorker,
	}
	return app, nil
}

// injector.go:

type App struct {
	DB     *gorm.DB
	Router *gin.Engine
	Worker *worker.ResizeImageJobWorker
}

func NewValidator() *validator.Validate {
	return validator.New()
}

var repositorySet = wire.NewSet(repository.NewMissingPersonRepository)

var usecaseSet = wire.NewSet(usecase.NewMissingPersonUsecase)

var controllerSet = wire.NewSet(controller.NewMissingPersonController)

var routerSet = wire.NewSet(router.SetupRouter)

func provideResizeImageWorker(db *gorm.DB) *worker.ResizeImageJobWorker {
	return worker.NewResizeImageJobWorker(db, 5)
}
